# Generated by Django 3.2.12 on 2022-07-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyisim', models.CharField(max_length=100, verbose_name='İsim-Soyisim')),
                ('hakkimda', models.TextField(max_length=300, verbose_name='Hakkımda')),
                ('resim', models.FileField(blank=True, null=True, upload_to='ogrenciResmi/', verbose_name='Öğrenci Resmi')),
            ],
        ),
    ]
