# Generated by Django 3.2.12 on 2022-07-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenciler', '0002_auto_20220712_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrenci',
            name='kategori',
        ),
        migrations.DeleteModel(
            name='Kategoriler',
        ),
    ]
